### PR TITLE
Make Java server

### PR DESCRIPTION
**Pull request by NGSpace**
(I fixed the issue with the previous PR)

I decided to use Java's built in "HttpServer" class instead of making my own way of interpreting HTTP requests.
I've also decided to use gradle as a buildtool.
Currently the HTML files are baked into the jar rather read from outside the jar but this can be changed in the future..

### CODE REVIEW

**Review by Dishpit — APPROVED** [review]
image

**Comment by Dishpit** [comment]
image

oh yeah, she's choochin'

**Comment by NGSpace** [comment]
I should've included build/execution instructions in the PR, it seems you figured it out but I'll still send them in this comment:

To build a jar run `./gradlew build` and the jar shall appear in `build/libs`

To execute without building a jar run `./gradlew run`

**Comment by Dishpit** [comment]
> I should've included build/execution instructions in the PR, it seems you figured it out but I'll still send them in this comment:
> 
> To build a jar run `./gradlew build` and the jar shall appear in `build/libs`
> 
> To execute without building a jar run `./gradlew run`

oh i just installed intellij idea and it detected the gradle script, hit the build button off to the side, then the run button at the top, as this is the only workflow i'm familiar with when it comes to java (introduced to it via intellij, which is barely functional on linux so i'm doing this from windows at the moment)

**Comment by NGSpace** [comment]
I haven't used IntelliJ on Linux since I prefer Eclipse but it's good that it worked.

It's pure Java so I knew that it would likely work but I didn't know if Windows would've had issues with approving the usage of the port or some other issue (as Windows tends to do).

**Pull request merged**
